# Generated by Django 4.2.6 on 2023-12-02 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0008_alter_clients_city_alter_clients_uf_delete_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeSubcategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=100, null=True)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revenues.recipecategories')),
            ],
        ),
        migrations.CreateModel(
            name='Revenues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('date_of_competence', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('delivery_date', models.DateField()),
                ('receipt_account', models.CharField(max_length=100)),
                ('receipt_status', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.clients')),
                ('subcategory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='revenues.recipesubcategories')),
            ],
        ),
    ]
