# Generated by Django 4.2.6 on 2023-12-02 02:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('revenues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenues',
            name='date_of_competence',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
