# Generated by Django 4.2.6 on 2023-12-02 03:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revenues', '0003_alter_revenues_date_of_competence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenues',
            name='delivery_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
