# Generated by Django 4.2.6 on 2023-12-04 20:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('revenues', '0005_recipecategories_autor_recipesubcategories_autor_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeCategories',
            new_name='RecipeCategoriesRevenues',
        ),
    ]
