# Generated by Django 4.2.6 on 2023-12-04 20:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('revenues', '0006_rename_recipecategories_recipecategoriesrevenues'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeSubcategories',
            new_name='RecipeSubcategoriesRevenues',
        ),
    ]
