# Generated by Django 4.2.6 on 2023-12-05 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_clients_autor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('revenues', '0007_rename_recipesubcategories_recipesubcategoriesrevenues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenues',
            name='autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='revenues_autor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='revenues',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenues_source', to='clients.clients'),
        ),
    ]
