# Generated by Django 4.2.6 on 2023-11-03 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('company_name', models.CharField(db_collation='Latin1_General_CI_AS', max_length=100, unique=True)),
                ('responsible_name', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', db_column='responsible_name', max_length=50, null=True)),
                ('cnpj_cpf', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=20, null=True)),
                ('contact', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=100, null=True)),
                ('city', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=50, null=True)),
                ('address', models.CharField(blank=True, db_collation='Latin1_General_CI_AS', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Clients',
            },
        ),
    ]
