# Generated by Django 4.2.6 on 2023-11-03 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'managed': False},
        ),
    ]
