# Generated by Django 4.2.6 on 2023-11-22 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.city'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='uf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.states'),
        ),
    ]
