# Generated by Django 4.2.6 on 2023-11-03 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_clients_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clients',
            table='Clientes',
        ),
    ]
