# Generated by Django 4.2.6 on 2023-11-03 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_clients_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clients',
            table='Clients',
        ),
    ]
