# Generated by Django 4.2.6 on 2023-11-06 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_clients_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={},
        ),
    ]
