# Generated by Django 4.2.6 on 2023-11-23 01:49

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_city_name_city_alter_clients_cnpj_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='uf', chained_model_field='uf', null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.city'),
        ),
    ]
