# Generated by Django 4.2.6 on 2023-11-06 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_clients_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_city', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='clients',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='cnpj_cpf',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='company_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='responsible_name',
            field=models.CharField(blank=True, db_column='responsible_name', max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='clients',
            table=None,
        ),
        migrations.AlterField(
            model_name='clients',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.city'),
        ),
    ]
