# Generated by Django 4.2.6 on 2023-11-23 02:18

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_clients_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='uf', chained_model_field='uf', on_delete=django.db.models.deletion.CASCADE, to='clients.city'),
        ),
    ]
