# Generated by Django 4.2.6 on 2023-11-24 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_clients_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.city'),
        ),
    ]
