# Generated by Django 4.2.6 on 2023-11-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_city_alter_clients_address_alter_clients_cnpj_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='cnpj_cpf',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
