# Generated by Django 4.2.6 on 2023-11-24 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0007_alter_clients_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100, unique=True)),
                ('seller_name', models.CharField(blank=True, db_column='responsible_name', max_length=50, null=True)),
                ('cnpj_cpf', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.city')),
                ('uf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.states')),
            ],
        ),
    ]
