# Generated by Django 4.2.6 on 2023-12-04 20:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0009_clients_autor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCategoriesExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('autor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeSubcategoriesExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=100, null=True)),
                ('autor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.recipecategoriesexpenses')),
            ],
        ),
        migrations.CreateModel(
            name='Revenues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('date_of_competence', models.DateField(default=datetime.datetime.now)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('delivery_date', models.DateField(default=datetime.datetime.now)),
                ('receipt_account', models.CharField(max_length=100)),
                ('receipt_status', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('autor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='revenues_autor', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revenues_source', to='clients.clients')),
                ('subcategory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='expenses.recipesubcategoriesexpenses')),
            ],
        ),
    ]
