# Generated by Django 4.2.6 on 2023-12-05 19:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCategoriesProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('autor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_of_measurement', models.CharField(max_length=100)),
                ('autor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeSubcategoriesProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=100, null=True)),
                ('autor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.recipecategoriesproducts')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_code', models.DateField(default=datetime.datetime.now, unique=True)),
                ('quantity_in_stock', models.CharField(max_length=100)),
                ('sale_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('location_in_stock', models.CharField(max_length=100)),
                ('availability', models.BooleanField(default=False)),
                ('comments', models.TextField(blank=True, null=True)),
                ('autor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products_autor', to=settings.AUTH_USER_MODEL)),
                ('subcategory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.recipesubcategoriesproducts')),
                ('unit_of_measurement', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.unitofmeasurement')),
            ],
        ),
    ]
