# Generated by Django 4.2.6 on 2023-12-11 19:22

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplier', '0003_supplier_autor'),
        ('products', '0002_alter_products_product_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=100)),
                ('unitary_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('entry_date', models.DateField(default=datetime.datetime.now)),
                ('invoice_number', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
                ('autor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products_entry_autor', to=settings.AUTH_USER_MODEL)),
                ('product_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.products')),
                ('supplier', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='supplier.supplier')),
                ('unit_of_measurement', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.unitofmeasurement')),
            ],
        ),
    ]
