# Generated by Django 4.2.6 on 2024-01-04 22:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplier', '0003_supplier_autor'),
        ('products', '0003_entryproducts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EntryProducts',
            new_name='EntryProductsForms',
        ),
        migrations.AlterField(
            model_name='products',
            name='product_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
