# Generated by Django 4.2.6 on 2024-01-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_entryproducts_entryproductsforms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='location_in_stock',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
